language: c++
sudo: required
services: docker
install:
- docker pull devkitpro/devkitppc
script:
- docker run -e ENABLE_COMPATIBILITY_REPORTING -v $TRAVIS_BUILD_DIR:/GameOfLife-Wii-ClubMatrix
  devkitpro/devkitppc /bin/bash -ex /GameOfLife-Wii-ClubMatrix/.travis/build.sh
deploy:
  provider: releases
  api_key:
    secure: k56iHH0Dm1hsSlqZvbzwrWOoRVC5Fzox1lzH9sXHwhimC6kUr4rnntYFYUlmYS7FjhVfnAs9WMkTEoa1VaRbIotJerAVjQhWn6oRZMhKK9sGG/Kd5xu8g8kSNvDV/AnQa88YGYVKaFrZuBMrr/gU4jDuW9j/GDkr5Ud5oxTM/d8ZEULgcQQ5C/YsSdcp0urrpd0ytLu66Zj/H76iufMw0J5QruGmR7sSnCNt4XnXYy34MXfQDnkuJ4A9vgGPlHZ0a8lzUa1BQ/TYRjnDgUvRBwqIE+F2m9Ijb7Agi8I2Vftq8JJN9wUGx3p7hvVn3Wr8xjt9VV+dLO6fgNMrGT9//rS6y7o9HUWnKdnq+kiXDeG4dvsxustzuewGjL5vj5VEXMsTmCdZHulOwAQ1gjEHFtu9istMlH+upUfksXit7jZH8Mn6C2+zC+wUdGOauLJdsvLb9i4PVVFqW6iLZ9K6S2ZOg8aEPQ5pofW1s9GxFdPTUU71BVPyLlfF6Bh41oLV0EL/XLbhP44ta+/5Kz5b2hRb2+aQK8O/msWj08iTwDHYj22Qv3+HIVb7jtNbRfw1L+ccoLG15KNZL2ckeN3bpXJe3c+ABwO7oskSoFd1xIFGLRwLJwryGDEV4acE3Rc5RO8ecJIy3ye69RPV2PrAl7k/pOiUXYBZGzFNdweQGNc=
  file: GameOfLife-Wii-ClubMatrix.elf
  on:
    repo: LgHS/GameOfLife-Wii-ClubMatrix
env:
  global:
    secure: iqlOc9nZ8nSdeMnHqxtZ/HrtUAnohMtjl1ZbvoL0dWqBX1KqOjOFrMSNAI3NbTRAwANk8Z/wukusJpK0t3Zx4pePntDMr2DsysHhiquAqZebNzAQIrb6T2rk2C3vXtNv5iGfnn3jg2A7iCEz0LnA5TiFdOaNhvwGK7CMsnMo+eRTnx2WvZXsYbCBKUVprRpCPjFzTbEBvaZ70UgZqTqIFmatmk705VJLWoiHGSiwp9ZyLpARMvrhUtZ9Wr8NWFieCLOcti+oPYc0dWaybK/qfVRHsqUFwJdejtdDx3BawwtsyvisC6EVh2zngUvvn1g1zx5vXemcUu1yc6Q4LgtF3dV3yfmcodHD3CkffaEzmeKoWWD6HmPI4P8wENosEG55uG53/eyeZIQ5Cil6Ey0JbJFRQujlxtFblkJ/TopR/m6XWcZc+QXsJtEWecgCSFV1fQ0liGzDeGycVuZmwQSWp9D2B1emaaaRiQ3DsRRfSlUI9MaiQYsPmALwD/wePs5elr1km+wbbKEQwTMy9ATcCFU8+3vt5AHzFXgb6HwjwOHNVqGYULcflqq44hYJWH7H76Mr2/5uK4v8SF4mT7FPzVV2Oje91GJkjSzpmlQ7F9NA9z3xoQTFW9OD5A93JJEe+ZMFw/HoI7JuaMB4GmqkKESqyjq2pIK+/LTgyIxu4bw=
